### ISSUE TITLE
Unable to change font size / color for labels

### ISSUE THREAD

**Issue by akhilhangout** [aritzfb/TreeCircle#10]
Thank you so much for building this helpful chart type.

Just downloaded the version 1.0.3 from marketplace.

I am unable to change / configure the color for the links.

I do not see an option to change the font size for tree labels.

**Comment by aritzfb** [comment]
Hello!
Thanks for try the visual!
I think you can't see the new features of the visual because it takes some time to release at all. It will take arround one month.
You have some workarround for fix this problem before it released:
If you are using PowerBI online, you can add at the end of your url this parameter:  '?approvedResourcesDisabled=true' See:  https://community.powerbi.com/t5/Developer/quot-pbiviz-package-quot-does-not-update-visual-s-capabilities/td-p/320266
Other option you can do it is downloading the code, and compile it with a different guid. If you don't know how to do it, you can use directly from the next url: https://github.com/aritzfb/TreeCircle/blob/master/dist/Pie%20Charts%20Tree.pbiviz

Regards

**Comment by akhilhangout** [comment]
Thanks. I used the pbviz, and it looks much better.
