### ISSUE TITLE
top level node total

### ISSUE THREAD

**Issue by urshah** [aritzfb/TreeCircle#2]
The top level node totals are not accurate. The more categories i add, the less the top level node total gets.
see the example below. add up the totals and it's 5297 but the top level node shows 3250. why is that? 

![image](https://user-images.githubusercontent.com/1085561/48840747-69008180-ed44-11e8-892b-a8468fae81fb.png)

**Comment by aritzfb** [comment]
Hello,

I think this issue was solved in the commit https://github.com/aritzfb/TreeCircle/commit/7683036f75d61d7e03395f295973ef6fe04d1de8
This change was inculded in the 1.0.2 published version, but it's posible that you are not seen this version. See this blog: https://community.powerbi.com/t5/Developer/quot-pbiviz-package-quot-does-not-update-visual-s-capabilities/td-p/320266
For fix this problem, you have 2 options:
Option 1: Download and compile any commit after the one what solve the bug (about the total value) changing the guid of the visual
Option 2: If you are using PowerBI.com (not the desktop app) you can solve the problem just adding the parameter '?approvedResourcesDisabled=true'
If the problem persist, please re-open the issue or create a new one.
Regards

**Comment by urshah** [comment]
i downloaded the app from the Power Bi marketplace. Why can i not download the latest version from there? I am using the power bi desktop version then publishing the report online.

**Comment by aritzfb** [comment]
Hello,
You are using the lastest version (1.0.2.0) but the api seems to be using the first version (1.0.1).
Please read this blog:
https://community.powerbi.com/t5/Developer/quot-pbiviz-package-quot-does-not-update-visual-s-capabilities/td-p/320266
Try to download and use this viz (last version of git with different guid): https://github.com/aritzfb/TreeCircle/blob/master/dist/Pie%20Charts%20Tree.pbiviz
